# Generated by Django 5.2.15 on 2026-06-08 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('clasificacion_imc', models.CharField(blank=True, max_length=50, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('glucosa', models.FloatField(blank=True, null=True)),
                ('colesterol', models.FloatField(blank=True, null=True)),
                ('saturacion_oxigeno', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnostico_preliminar', models.CharField(blank=True, max_length=250, null=True)),
                ('riesgo_enfermedad', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('registros_procesados', models.IntegerField()),
                ('tiempo_ejecucion', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
