# Generated by Django 4.2 on 2026-06-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialetl',
            name='errores_encontrados',
            field=models.IntegerField(default=0),
        ),
    ]
