# Generated by Django 4.2 on 2026-06-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardKPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('pacientes_criticos', models.IntegerField(default=0)),
                ('pacientes_hipertensos', models.IntegerField(default=0)),
                ('pacientes_diabeticos', models.IntegerField(default=0)),
                ('pacientes_fumadores', models.IntegerField(default=0)),
                ('riesgo_promedio', models.FloatField(default=0.0)),
                ('edad_media', models.FloatField(default=0.0)),
                ('edad_mediana', models.FloatField(default=0.0)),
                ('edad_moda', models.FloatField(default=0.0)),
                ('edad_desviacion', models.FloatField(default=0.0)),
                ('glucosa_media', models.FloatField(default=0.0)),
                ('glucosa_desviacion', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
