# Generated by Django 5.2.15 on 2026-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_dashboardkpis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasModeloML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('matriz_confusion', models.JSONField()),
                ('modelo_activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
